name: shopping_website
description: Welcome to shopping website, your shopping destination for fashion online.
 We offer fashion and quality at the best price in a more sustainable way.



version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1

dev_dependencies:
 
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    
  
 